In [1]:
# Cell 1: Import and create arrays
import numpy as np

# Create arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(f"1D array: {arr1}")
print(f"2D array:\n{arr2}")
print(f"Shape of arr2: {arr2.shape}")

1D array: [1 2 3 4 5]
2D array:
[[1 2 3]
 [4 5 6]]
Shape of arr2: (2, 3)


In [3]:
# Cell 2: Array operations (CRITICAL for image processing!)
# Images are just arrays of numbers!

# Creating a 5x5 array (tiny grayscale image)
image = np.array([
    [100, 120, 130, 140, 150],
    [110, 125, 135, 145, 155],
    [105, 115, 125, 135, 145],
    [95,  105, 115, 125, 135],
    [90,  100, 110, 120, 130]
])

print("Image (5x5 pixels):")
print(image)
print(f"Image shape: {image.shape}")
print(f"Pixel at row 0, col 0: {image[0, 0]}")
print(f"Top row: {image[0, :]}")
print(f"First column: {image[:, 0]}")

Image (5x5 pixels):
[[100 120 130 140 150]
 [110 125 135 145 155]
 [105 115 125 135 145]
 [ 95 105 115 125 135]
 [ 90 100 110 120 130]]
Image shape: (5, 5)
Pixel at row 0, col 0: 100
Top row: [100 120 130 140 150]
First column: [100 110 105  95  90]


In [5]:
# Cell 3: Array math (processing image)
# Brighten image (add 50 to all pixels)
brightened = image + 50
print("Brightened image:")
print(brightened)

# Darken image
darkened = image - 30
print("Darkened image:")
print(darkened)

# Increase contrast (multiply)
contrast = image * 1.5
print("Higher contrast:")
print(contrast.astype(int))  # Convert to int

Brightened image:
[[150 170 180 190 200]
 [160 175 185 195 205]
 [155 165 175 185 195]
 [145 155 165 175 185]
 [140 150 160 170 180]]
Darkened image:
[[ 70  90 100 110 120]
 [ 80  95 105 115 125]
 [ 75  85  95 105 115]
 [ 65  75  85  95 105]
 [ 60  70  80  90 100]]
Higher contrast:
[[150 180 195 210 225]
 [165 187 202 217 232]
 [157 172 187 202 217]
 [142 157 172 187 202]
 [135 150 165 180 195]]


In [7]:
# Cell 4: Boolean Indexing (for thresholding - finding objects)
# Find all pixels brighter than 120
bright_pixels = image > 120
print("Pixels brighter than 120:")
print(bright_pixels)

# Count
count = np.sum(bright_pixels)
print(f"Number of bright pixels: {count}")

# Set all dark pixels to 0 (like removing background)
threshold = 115
cleaned = np.where(image > threshold, image, 0)
print("After thresholding:")
print(cleaned)

Pixels brighter than 120:
[[False False  True  True  True]
 [False  True  True  True  True]
 [False False  True  True  True]
 [False False False  True  True]
 [False False False False  True]]
Number of bright pixels: 13
After thresholding:
[[  0 120 130 140 150]
 [  0 125 135 145 155]
 [  0   0 125 135 145]
 [  0   0   0 125 135]
 [  0   0   0 120 130]]


In [10]:
# Cell 5: Practice with realistic image dimensions
# Real image are much bigger, e.g., 1920x1000 pixels

# Create random "image" (1920x1000)
large_image = np.random.randint(0, 256, size=(1000, 1920))
print(f"Large image shape: {large_image.shape}")
print(f"First 5x5 pixels:\n{large_image[:5, :5]}")

# Calculate statistics (will do a lot)
print(f"Mean brightness: np.mean(large_image):.2f")
print(f"Std deviation: {np.std(large_image):.2f}")
print(f"Min: {np.min(large_image)}, Max: {np.max(large_image)}")


Large image shape: (1000, 1920)
First 5x5 pixels:
[[174   3   2 252 163]
 [133 120 213 148  96]
 [ 70  47  25   5  29]
 [130  75  89  63 215]
 [105 213 157 223  98]]
Mean brightness: np.mean(large_image):.2f
Std deviation: 73.90
Min: 0, Max: 255


In [18]:
# Practice
# Create 100x100 array, set a centered 50x50 block to 255 (white) and rest 0 (black).

import numpy as np

def set_center_white(image, square_size=50, value=255):
    h, w = image.shape[:2]
    s = min(square_size, h, w)
    top = (h - s) // 2
    left = (w - s) // 2
    if image.ndim == 2:
        image[top:top+s, left:left+s] = value
    else:
        image[top:top+s, left:left+s, :] = value
    return image

# Create a black image (uint8) and set center square to white
image = np.zeros((100, 100), dtype=np.uint8)
image = set_center_white(image, square_size=50, value=255)

# Count white pixels and compute percentage
white_count = np.count_nonzero(image == 255)
total_pixels = image.size
white_percent = white_count / total_pixels * 100
print(f"White pixels: {white_count} / {total_pixels} ({white_percent:.2f}%)")

# Verify by explicit boolean mask (same result)
mask = (image == 255)
print(f"Mask sum (should match white_count): {np.sum(mask)}")

# Threshold example: keep pixels > 200, others set to 0
threshold = 200
cleaned = np.where(image > threshold, image, 0)
print("After thresholding:", np.unique(cleaned))

White pixels: 2500 / 10000 (25.00%)
Mask sum (should match white_count): 2500
After thresholding: [  0 255]
